using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows;

namespace OpenTuner.Wpf
{
    /// <summary>
    /// Runtime localization for the WPF UI.
    ///
    /// English is the master catalogue. Every other language supplies overrides
    /// (anything missing falls back to English). <see cref="Apply"/> publishes the
    /// resolved strings into <see cref="Application.Resources"/> so XAML can bind
    /// text with <c>{DynamicResource key}</c> and update live when the language
    /// changes. Code-behind strings use <see cref="Get"/>.
    /// </summary>
    public static class LocalizationManager
    {
        public static string CurrentLanguage { get; private set; } = "en";

        public static event Action LanguageChanged;

        /// <summary>Code -> native display name, in menu order.</summary>
        public static readonly (string Code, string Name)[] Languages =
        {
            ("en", "English"),
            ("af", "Afrikaans"),
            ("de", "Deutsch"),
            ("es", "Espa\u00f1ol"),
            ("it", "Italiano"),
            ("ja", "\u65e5\u672c\u8a9e"),
            ("nl", "Nederlands"),
            ("pl", "Polski")
        };

        // ------------------------------------------------------------------
        // master (English) catalogue
        // ------------------------------------------------------------------
        private static readonly Dictionary<string, string> En = new Dictionary<string, string>
        {
            // ---- top-level menus ----
            { "mw.menu.open", "Open Tuner" },
            { "mw.menu.settings", "Settings..." },
            { "mw.menu.presets", "Manage Frequency Presets..." },
            { "mw.menu.disconnect", "Disconnect" },
            { "mw.menu.dark", "Dark mode" },
            { "mw.menu.contrast", "High contrast" },
            { "mw.menu.language", "Language" },
            { "mw.menu.quit", "Quit" },
            { "mw.menu.view", "View" },
            { "mw.menu.tune", "Tune to Frequency..." },
            { "mw.menu.fullscreen", "Full Screen" },
            { "mw.menu.layout", "Layout presets" },
            { "mw.layout.1", "Single" },
            { "mw.layout.2side", "Two - side by side" },
            { "mw.layout.2stack", "Two - stacked" },
            { "mw.layout.4quad", "Four - quad" },
            { "mw.menu.hideprops", "Hide Properties" },
            { "mw.menu.hidespectrum", "Hide Spectrum" },
            { "mw.menu.shortcuts", "Keyboard Shortcuts..." },
            { "mw.menu.debuglog", "Debug Log..." },
            { "mw.menu.features", "Features" },
            { "mw.menu.mqttsettings", "MQTT Client Settings..." },
            { "mw.menu.quicktunesettings", "QuickTune Settings..." },
            { "mw.menu.datvsettings", "DATV Reporter Settings..." },
            { "mw.menu.webchatsettings", "Web Chat Settings..." },
            { "mw.menu.qrzsettings", "QRZ Lookup Settings..." },
            { "mw.menu.webchat", "Web Chat..." },
            { "mw.menu.broadcastlistener", "PicoTuner (WH) Broadcast Listener..." },
            { "mw.menu.hardwareinfo", "Hardware Info..." },
            { "mw.menu.externaltools", "External Tools..." },
            { "mw.menu.pluto", "Pluto Control..." },
            { "mw.menu.bandscan", "Band Scan..." },
            { "mw.menu.beacons", "QO-100 Beacons..." },
            { "mw.menu.qsolog", "QSO Log..." },
            { "mw.menu.recordmanager", "Record Manager..." },
            { "mw.menu.gallery", "Snapshot Gallery..." },
            { "mw.menu.help", "Help" },
            { "mw.menu.documentation", "Documentation" },
            { "mw.menu.updates", "OpenTuner Updates" },
            { "mw.menu.github", "GitHub Issues" },
            { "mw.menu.forums", "BATC Forums" },
            { "mw.menu.batc", "British Amateur Television Club" },
            { "mw.menu.article2ndts", "Add 2nd TS to Minitiouner Article" },
            { "mw.menu.articlepico", "PicoTuner Article" },
            { "mw.menu.support", "Support (Buy me a coffee)" },

            // ---- main window cards / controls ----
            { "mw.card.source", "SOURCE SELECTION" },
            { "mw.connect", "Connect" },
            { "mw.sourcesettings", "Source Settings" },
            { "mw.card.extra", "EXTRA FEATURES" },
            { "mw.info", "Info" },
            { "mw.settings", "Settings" },
            { "mw.chk.batcspectrum", "BATC Spectrum (QO-100)" },
            { "mw.chk.batchat", "BATC Chat (QO-100)" },
            { "mw.chk.mqtt", "MQTT Client" },
            { "mw.chk.quicktune", "Quick Tune Control" },
            { "mw.chk.datv", "DATV Reporter" },
            { "mw.chk.sdr", "SDR Spectrum" },
            { "mw.chk.qrz", "QRZ Lookup" },
            { "mw.card.properties", "PROPERTIES" },
            { "mw.nosource", "No source connected" },
            { "mw.rx", "RX" },
            { "mw.tunestrongest", "Tune strongest" },
            { "mw.sdrsettings", "SDR Settings..." },
            { "mw.tab.batc", "BATC Spectrum" },
            { "mw.tab.sdr", "SDR Spectrum" },
            { "mw.tab.signal", "Signal History" },
            { "mw.tab.qso", "QSO Log" },
            { "mw.tab.debug", "Debug" },
            { "mw.clear", "Clear" },
            { "mw.graph.show", "Show:" },
            { "mw.graph.mer", "SNR/MER" },
            { "mw.graph.margin", "Margin" },
            { "mw.graph.ber", "BER" },
            { "mw.graph.window", "Window:" },

            // ---- status bar ----
            { "mw.status.source", "Source" },
            { "mw.status.device", "Device" },
            { "mw.status.lock", "Lock" },
            { "mw.status.disk", "Disk" },
            { "mw.status.yes", "YES" },
            { "mw.status.no", "no" },
            { "mw.status.free", "free" },

            // ---- messages / toasts ----
            { "msg.connectsource", "Connect to a source first." },
            { "mw.toast.locked", "Signal locked" },
            { "mw.toast.lost", "Signal lost" },
            { "mw.toast.recstart", "Recording started" },
            { "mw.toast.recstop", "Recording stopped" },
            { "mw.toast.snapshot", "Snapshot taken" },
            { "mw.toast.tuned", "Tuned to" },
            { "mw.toast.exported", "Exported" },
            { "mw.toast.imported", "Imported" },
            { "mw.toast.rows", "row(s)" },
            { "mw.toast.presets", "preset(s)" },

            // ---- dialog titles ----
            { "dt.settings", "Settings" },
            { "dt.tune", "Tune to Frequency" },
            { "dt.presets", "Frequency Presets" },
            { "dt.broadcast", "PicoTuner (WH) Broadcast Listener" },
            { "dt.hardware", "Hardware Info" },
            { "dt.externaltools", "External Tools" },
            { "dt.pluto", "Pluto Control (F5OEO)" },
            { "dt.webchat", "QO-100 Wideband Chat" },
            { "dt.beacons", "QO-100 Bandplan / Beacons" },
            { "dt.bandscan", "Band Scan" },
            { "dt.recordmanager", "Record Manager" },
            { "dt.gallery", "Snapshot Gallery" },
            { "dt.shortcuts", "Keyboard Shortcuts" },
            { "dt.qrz", "QRZ Lookup" },
            { "dt.debug", "Debug" },

            // ---- buttons ----
            { "btn.save", "Save" },
            { "btn.cancel", "Cancel" },
            { "btn.close", "Close" },
            { "btn.add", "Add" },
            { "btn.start", "Start" },
            { "btn.stop", "Stop" },
            { "btn.refresh", "Refresh" },
            { "btn.delete", "Delete" },
            { "btn.play", "Play" },
            { "btn.pause", "Pause" },
            { "btn.export", "Export" },
            { "btn.import", "Import" }
        };

        // ------------------------------------------------------------------
        // per-language overrides
        // ------------------------------------------------------------------
        private static readonly Dictionary<string, Dictionary<string, string>> Overrides =
            new Dictionary<string, Dictionary<string, string>>(StringComparer.OrdinalIgnoreCase)
        {
            { "af", new Dictionary<string, string>
                {
                    { "mw.menu.open", "Open Tuner" },
                    { "mw.menu.settings", "Instellings..." },
                    { "mw.menu.presets", "Bestuur frekwensie-voorinstellings..." },
                    { "mw.menu.disconnect", "Ontkoppel" },
                    { "mw.menu.dark", "Donker modus" },
                    { "mw.menu.contrast", "Ho\u00eb kontras" },
                    { "mw.menu.language", "Taal" },
                    { "mw.menu.quit", "Sluit af" },
                    { "mw.menu.view", "Vertoon" },
                    { "mw.menu.tune", "Stem op frekwensie..." },
                    { "mw.menu.fullscreen", "Volskerm" },
                    { "mw.menu.layout", "Uitleg-voorafinstellings" },
                    { "mw.layout.1", "Enkel" },
                    { "mw.layout.2side", "Twee - langs mekaar" },
                    { "mw.layout.2stack", "Twee - gestapel" },
                    { "mw.layout.4quad", "Vier - kwadrant" },
                    { "mw.menu.hideprops", "Versteek eienskappe" },
                    { "mw.menu.hidespectrum", "Versteek spektrum" },
                    { "mw.menu.shortcuts", "Sneltoetse..." },
                    { "mw.menu.debuglog", "Ontfoutlog..." },
                    { "mw.menu.features", "Kenmerke" },
                    { "mw.menu.webchat", "Webklets..." },
                    { "mw.menu.hardwareinfo", "Hardeware-inligting..." },
                    { "mw.menu.externaltools", "Eksterne gereedskap..." },
                    { "mw.menu.pluto", "Pluto-beheer..." },
                    { "mw.menu.bandscan", "Bandskandering..." },
                    { "mw.menu.beacons", "QO-100 bakens..." },
                    { "mw.menu.recordmanager", "Opnamebestuurder..." },
                    { "mw.menu.gallery", "Kiekie-galery..." },
                    { "mw.menu.help", "Hulp" },
                    { "mw.menu.documentation", "Dokumentasie" },
                    { "mw.card.source", "BRONKEUSE" },
                    { "mw.connect", "Verbind" },
                    { "mw.sourcesettings", "Bron-instellings" },
                    { "mw.card.extra", "EKSTRA KENMERKE" },
                    { "mw.info", "Inligting" },
                    { "mw.settings", "Instellings" },
                    { "mw.chk.batcspectrum", "BATC-spektrum (QO-100)" },
                    { "mw.chk.batchat", "BATC-klets (QO-100)" },
                    { "mw.chk.mqtt", "MQTT-kli\u00ebnt" },
                    { "mw.chk.quicktune", "Vinnige instemming" },
                    { "mw.chk.datv", "DATV-aanmeld" },
                    { "mw.chk.sdr", "SDR-spektrum" },
                    { "mw.chk.qrz", "QRZ-soektog" },
                    { "mw.card.properties", "EIENSKAPPE" },
                    { "mw.nosource", "Geen bron gekoppel" },
                    { "mw.rx", "RX" },
                    { "mw.tunestrongest", "Stem op sterkste" },
                    { "mw.sdrsettings", "SDR-instellings..." },
                    { "mw.tab.batc", "BATC-spektrum" },
                    { "mw.tab.sdr", "SDR-spektrum" },
                    { "mw.tab.signal", "Seingeskiedenis" },
                    { "mw.tab.debug", "Ontfout" },
                    { "mw.clear", "Vee uit" },
                    { "mw.graph.show", "Wys:" },
                    { "mw.graph.mer", "SNR/MER" },
                    { "mw.graph.margin", "Marge" },
                    { "mw.graph.ber", "BER" },
                    { "mw.graph.window", "Venster:" },
                    { "mw.status.source", "Bron" },
                    { "mw.status.device", "Toestel" },
                    { "mw.status.lock", "Slot" },
                    { "mw.status.disk", "Skyf" },
                    { "mw.status.yes", "JA" },
                    { "mw.status.no", "nee" },
                    { "mw.status.free", "vry" },
                    { "msg.connectsource", "Verbind eers aan 'n bron." },
                    { "mw.toast.locked", "Sein gesluit" },
                    { "mw.toast.lost", "Sein verloor" },
                    { "mw.toast.recstart", "Opname begin" },
                    { "mw.toast.recstop", "Opname gestop" },
                    { "mw.toast.snapshot", "Kiekie geneem" },
                    { "mw.toast.tuned", "Ingestem op" },
                    { "btn.save", "Stoor" },
                    { "btn.cancel", "Kanselleer" },
                    { "btn.close", "Sluit" },
                    { "btn.add", "Voeg by" },
                    { "btn.start", "Begin" },
                    { "btn.stop", "Stop" },
                    { "btn.refresh", "Ver Vers" },
                    { "btn.delete", "Verwyder" },
                    { "btn.play", "Speel" },
                    { "btn.pause", "Pouse" },
                    { "btn.export", "Voer uit" },
                    { "btn.import", "Voer in" },
                }
            },
            { "de", new Dictionary<string, string>
                {
                    { "mw.menu.open", "Open Tuner" },
                    { "mw.menu.settings", "Einstellungen..." },
                    { "mw.menu.presets", "Frequenzvoreinstellungen verwalten..." },
                    { "mw.menu.disconnect", "Trennen" },
                    { "mw.menu.dark", "Dunkelmodus" },
                    { "mw.menu.contrast", "Hoher Kontrast" },
                    { "mw.menu.language", "Sprache" },
                    { "mw.menu.quit", "Beenden" },
                    { "mw.menu.view", "Ansicht" },
                    { "mw.menu.tune", "Auf Frequenz abstimmen..." },
                    { "mw.menu.fullscreen", "Vollbild" },
                    { "mw.menu.layout", "Layout-Voreinstellungen" },
                    { "mw.layout.1", "Einzeln" },
                    { "mw.layout.2side", "Zwei - nebeneinander" },
                    { "mw.layout.2stack", "Zwei - \u00fcbereinander" },
                    { "mw.layout.4quad", "Vier - Quadrant" },
                    { "mw.menu.hideprops", "Eigenschaften ausblenden" },
                    { "mw.menu.hidespectrum", "Spektrum ausblenden" },
                    { "mw.menu.shortcuts", "Tastenk\u00fcrzel..." },
                    { "mw.menu.debuglog", "Debug-Protokoll..." },
                    { "mw.menu.features", "Funktionen" },
                    { "mw.menu.mqttsettings", "MQTT-Client-Einstellungen..." },
                    { "mw.menu.quicktunesettings", "QuickTune-Einstellungen..." },
                    { "mw.menu.datvsettings", "DATV-Reporter-Einstellungen..." },
                    { "mw.menu.webchatsettings", "Webchat-Einstellungen..." },
                    { "mw.menu.qrzsettings", "QRZ-Suche-Einstellungen..." },
                    { "mw.menu.webchat", "Webchat..." },
                    { "mw.menu.broadcastlistener", "PicoTuner (WH) Broadcast-Listener..." },
                    { "mw.menu.hardwareinfo", "Hardware-Info..." },
                    { "mw.menu.externaltools", "Externe Werkzeuge..." },
                    { "mw.menu.pluto", "Pluto-Steuerung..." },
                    { "mw.menu.bandscan", "Bandsuchlauf..." },
                    { "mw.menu.beacons", "QO-100 Baken..." },
                    { "mw.menu.recordmanager", "Aufnahmeverwaltung..." },
                    { "mw.menu.gallery", "Schnappschuss-Galerie..." },
                    { "mw.menu.help", "Hilfe" },
                    { "mw.menu.documentation", "Dokumentation" },
                    { "mw.menu.updates", "OpenTuner-Updates" },
                    { "mw.menu.github", "GitHub-Probleme" },
                    { "mw.menu.forums", "BATC-Foren" },
                    { "mw.menu.batc", "British Amateur Television Club" },
                    { "mw.menu.article2ndts", "Artikel: 2. TS am Minitiouner" },
                    { "mw.menu.articlepico", "PicoTuner-Artikel" },
                    { "mw.menu.support", "Unterst\u00fctzung (Kauf mir einen Kaffee)" },
                    { "mw.card.source", "QUELLENAUSWAHL" },
                    { "mw.connect", "Verbinden" },
                    { "mw.sourcesettings", "Quelleneinstellungen" },
                    { "mw.card.extra", "ZUSATZFUNKTIONEN" },
                    { "mw.info", "Info" },
                    { "mw.settings", "Einstellungen" },
                    { "mw.chk.batcspectrum", "BATC-Spektrum (QO-100)" },
                    { "mw.chk.batchat", "BATC-Chat (QO-100)" },
                    { "mw.chk.mqtt", "MQTT-Client" },
                    { "mw.chk.quicktune", "Quick Tune" },
                    { "mw.chk.datv", "DATV-Reporter" },
                    { "mw.chk.sdr", "SDR-Spektrum" },
                    { "mw.chk.qrz", "QRZ-Suche" },
                    { "mw.card.properties", "EIGENSCHAFTEN" },
                    { "mw.nosource", "Keine Quelle verbunden" },
                    { "mw.rx", "RX" },
                    { "mw.tunestrongest", "St\u00e4rkstes abstimmen" },
                    { "mw.sdrsettings", "SDR-Einstellungen..." },
                    { "mw.tab.batc", "BATC-Spektrum" },
                    { "mw.tab.sdr", "SDR-Spektrum" },
                    { "mw.tab.signal", "Signalverlauf" },
                    { "mw.tab.debug", "Debug" },
                    { "mw.clear", "Leeren" },
                    { "mw.graph.show", "Anzeigen:" },
                    { "mw.graph.mer", "SNR/MER" },
                    { "mw.graph.margin", "Marge" },
                    { "mw.graph.ber", "BER" },
                    { "mw.graph.window", "Zeitraum:" },
                    { "mw.status.source", "Quelle" },
                    { "mw.status.device", "Ger\u00e4t" },
                    { "mw.status.lock", "Sperre" },
                    { "mw.status.disk", "Datentr\u00e4ger" },
                    { "mw.status.yes", "JA" },
                    { "mw.status.no", "nein" },
                    { "mw.status.free", "frei" },
                    { "msg.connectsource", "Zuerst eine Quelle verbinden." },
                    { "mw.toast.locked", "Signal eingerastet" },
                    { "mw.toast.lost", "Signal verloren" },
                    { "mw.toast.recstart", "Aufnahme gestartet" },
                    { "mw.toast.recstop", "Aufnahme gestoppt" },
                    { "mw.toast.snapshot", "Schnappschuss erstellt" },
                    { "mw.toast.tuned", "Abgestimmt auf" },
                    { "btn.save", "Speichern" },
                    { "btn.cancel", "Abbrechen" },
                    { "btn.close", "Schlie\u00dfen" },
                    { "btn.add", "Hinzuf\u00fcgen" },
                    { "btn.start", "Start" },
                    { "btn.stop", "Stopp" },
                    { "btn.refresh", "Aktualisieren" },
                    { "btn.delete", "L\u00f6schen" },
                    { "btn.play", "Wiedergabe" },
                    { "btn.pause", "Pause" },
                    { "btn.export", "Exportieren" },
                    { "btn.import", "Importieren" },
                }
            },
            { "es", new Dictionary<string, string>
                {
                    { "mw.menu.open", "Open Tuner" },
                    { "mw.menu.settings", "Configuraci\u00f3n..." },
                    { "mw.menu.presets", "Gestionar preajustes de frecuencia..." },
                    { "mw.menu.disconnect", "Desconectar" },
                    { "mw.menu.dark", "Modo oscuro" },
                    { "mw.menu.contrast", "Alto contraste" },
                    { "mw.menu.language", "Idioma" },
                    { "mw.menu.quit", "Salir" },
                    { "mw.menu.view", "Ver" },
                    { "mw.menu.tune", "Sintonizar frecuencia..." },
                    { "mw.menu.fullscreen", "Pantalla completa" },
                    { "mw.menu.layout", "Preajustes de dise\u00f1o" },
                    { "mw.layout.1", "Uno" },
                    { "mw.layout.2side", "Dos - lado a lado" },
                    { "mw.layout.2stack", "Dos - apilados" },
                    { "mw.layout.4quad", "Cuatro - cuadr\u00edcula" },
                    { "mw.menu.hideprops", "Ocultar propiedades" },
                    { "mw.menu.hidespectrum", "Ocultar espectro" },
                    { "mw.menu.shortcuts", "Atajos de teclado..." },
                    { "mw.menu.debuglog", "Registro de depuraci\u00f3n..." },
                    { "mw.menu.features", "Funciones" },
                    { "mw.menu.mqttsettings", "Configuraci\u00f3n del cliente MQTT..." },
                    { "mw.menu.quicktunesettings", "Configuraci\u00f3n de QuickTune..." },
                    { "mw.menu.datvsettings", "Configuraci\u00f3n de DATV Reporter..." },
                    { "mw.menu.webchatsettings", "Configuraci\u00f3n del chat web..." },
                    { "mw.menu.qrzsettings", "Configuraci\u00f3n de b\u00fasqueda QRZ..." },
                    { "mw.menu.webchat", "Chat web..." },
                    { "mw.menu.broadcastlistener", "Receptor de difusi\u00f3n PicoTuner (WH)..." },
                    { "mw.menu.hardwareinfo", "Informaci\u00f3n de hardware..." },
                    { "mw.menu.externaltools", "Herramientas externas..." },
                    { "mw.menu.pluto", "Control de Pluto..." },
                    { "mw.menu.bandscan", "Exploraci\u00f3n de banda..." },
                    { "mw.menu.beacons", "Balizas QO-100..." },
                    { "mw.menu.recordmanager", "Gestor de grabaciones..." },
                    { "mw.menu.gallery", "Galer\u00eda de capturas..." },
                    { "mw.menu.help", "Ayuda" },
                    { "mw.menu.documentation", "Documentaci\u00f3n" },
                    { "mw.menu.updates", "Actualizaciones de OpenTuner" },
                    { "mw.menu.github", "Problemas en GitHub" },
                    { "mw.menu.forums", "Foros BATC" },
                    { "mw.menu.batc", "British Amateur Television Club" },
                    { "mw.menu.article2ndts", "Art\u00edculo: 2.\u00ba TS en Minitiouner" },
                    { "mw.menu.articlepico", "Art\u00edculo de PicoTuner" },
                    { "mw.menu.support", "Apoyar (inv\u00edtame a un caf\u00e9)" },
                    { "mw.card.source", "SELECCI\u00d3N DE FUENTE" },
                    { "mw.connect", "Conectar" },
                    { "mw.sourcesettings", "Configuraci\u00f3n de la fuente" },
                    { "mw.card.extra", "FUNCIONES EXTRA" },
                    { "mw.info", "Info" },
                    { "mw.settings", "Configuraci\u00f3n" },
                    { "mw.chk.batcspectrum", "Espectro BATC (QO-100)" },
                    { "mw.chk.batchat", "Chat BATC (QO-100)" },
                    { "mw.chk.mqtt", "Cliente MQTT" },
                    { "mw.chk.quicktune", "Quick Tune" },
                    { "mw.chk.datv", "DATV Reporter" },
                    { "mw.chk.sdr", "Espectro SDR" },
                    { "mw.chk.qrz", "B\u00fasqueda QRZ" },
                    { "mw.card.properties", "PROPIEDADES" },
                    { "mw.nosource", "Ninguna fuente conectada" },
                    { "mw.rx", "RX" },
                    { "mw.tunestrongest", "Sintonizar la m\u00e1s fuerte" },
                    { "mw.sdrsettings", "Configuraci\u00f3n SDR..." },
                    { "mw.tab.batc", "Espectro BATC" },
                    { "mw.tab.sdr", "Espectro SDR" },
                    { "mw.tab.signal", "Historial de se\u00f1al" },
                    { "mw.tab.debug", "Depuraci\u00f3n" },
                    { "mw.clear", "Borrar" },
                    { "mw.graph.show", "Mostrar:" },
                    { "mw.graph.mer", "SNR/MER" },
                    { "mw.graph.margin", "Margen" },
                    { "mw.graph.ber", "BER" },
                    { "mw.graph.window", "Ventana:" },
                    { "mw.status.source", "Fuente" },
                    { "mw.status.device", "Dispositivo" },
                    { "mw.status.lock", "Bloqueo" },
                    { "mw.status.disk", "Disco" },
                    { "mw.status.yes", "S\u00cd" },
                    { "mw.status.no", "no" },
                    { "mw.status.free", "libres" },
                    { "msg.connectsource", "Conecte primero una fuente." },
                    { "mw.toast.locked", "Se\u00f1al fijada" },
                    { "mw.toast.lost", "Se\u00f1al perdida" },
                    { "mw.toast.recstart", "Grabaci\u00f3n iniciada" },
                    { "mw.toast.recstop", "Grabaci\u00f3n detenida" },
                    { "mw.toast.snapshot", "Captura tomada" },
                    { "mw.toast.tuned", "Sintonizado en" },
                    { "btn.save", "Guardar" },
                    { "btn.cancel", "Cancelar" },
                    { "btn.close", "Cerrar" },
                    { "btn.add", "A\u00f1adir" },
                    { "btn.start", "Iniciar" },
                    { "btn.stop", "Detener" },
                    { "btn.refresh", "Actualizar" },
                    { "btn.delete", "Eliminar" },
                    { "btn.play", "Reproducir" },
                    { "btn.pause", "Pausa" },
                    { "btn.export", "Exportar" },
                    { "btn.import", "Importar" },
                }
            },
            { "it", new Dictionary<string, string>
                {
                    { "mw.menu.open", "Open Tuner" },
                    { "mw.menu.settings", "Impostazioni..." },
                    { "mw.menu.presets", "Gestisci preselezioni di frequenza..." },
                    { "mw.menu.disconnect", "Disconnetti" },
                    { "mw.menu.dark", "Modalit\u00e0 scura" },
                    { "mw.menu.contrast", "Alto contrasto" },
                    { "mw.menu.language", "Lingua" },
                    { "mw.menu.quit", "Esci" },
                    { "mw.menu.view", "Visualizza" },
                    { "mw.menu.tune", "Sintonizza frequenza..." },
                    { "mw.menu.fullscreen", "Schermo intero" },
                    { "mw.menu.layout", "Preselezioni layout" },
                    { "mw.layout.1", "Singolo" },
                    { "mw.layout.2side", "Due - affiancati" },
                    { "mw.layout.2stack", "Due - sovrapposti" },
                    { "mw.layout.4quad", "Quattro - griglia" },
                    { "mw.menu.hideprops", "Nascondi propriet\u00e0" },
                    { "mw.menu.hidespectrum", "Nascondi spettro" },
                    { "mw.menu.shortcuts", "Scorciatoie da tastiera..." },
                    { "mw.menu.debuglog", "Registro di debug..." },
                    { "mw.menu.features", "Funzioni" },
                    { "mw.menu.mqttsettings", "Impostazioni client MQTT..." },
                    { "mw.menu.quicktunesettings", "Impostazioni QuickTune..." },
                    { "mw.menu.datvsettings", "Impostazioni DATV Reporter..." },
                    { "mw.menu.webchatsettings", "Impostazioni chat web..." },
                    { "mw.menu.qrzsettings", "Impostazioni ricerca QRZ..." },
                    { "mw.menu.webchat", "Chat web..." },
                    { "mw.menu.broadcastlistener", "Listener broadcast PicoTuner (WH)..." },
                    { "mw.menu.hardwareinfo", "Informazioni hardware..." },
                    { "mw.menu.externaltools", "Strumenti esterni..." },
                    { "mw.menu.pluto", "Controllo Pluto..." },
                    { "mw.menu.bandscan", "Scansione banda..." },
                    { "mw.menu.beacons", "Fari QO-100..." },
                    { "mw.menu.recordmanager", "Gestione registrazioni..." },
                    { "mw.menu.gallery", "Galleria istantanee..." },
                    { "mw.menu.help", "Aiuto" },
                    { "mw.menu.documentation", "Documentazione" },
                    { "mw.menu.updates", "Aggiornamenti OpenTuner" },
                    { "mw.menu.github", "Problemi su GitHub" },
                    { "mw.menu.forums", "Forum BATC" },
                    { "mw.menu.batc", "British Amateur Television Club" },
                    { "mw.menu.article2ndts", "Articolo: 2\u00ba TS su Minitiouner" },
                    { "mw.menu.articlepico", "Articolo PicoTuner" },
                    { "mw.menu.support", "Supporto (offrimi un caff\u00e8)" },
                    { "mw.card.source", "SELEZIONE SORGENTE" },
                    { "mw.connect", "Connetti" },
                    { "mw.sourcesettings", "Impostazioni sorgente" },
                    { "mw.card.extra", "FUNZIONI EXTRA" },
                    { "mw.info", "Info" },
                    { "mw.settings", "Impostazioni" },
                    { "mw.chk.batcspectrum", "Spettro BATC (QO-100)" },
                    { "mw.chk.batchat", "Chat BATC (QO-100)" },
                    { "mw.chk.mqtt", "Client MQTT" },
                    { "mw.chk.quicktune", "Sintonizzazione rapida" },
                    { "mw.chk.datv", "DATV Reporter" },
                    { "mw.chk.sdr", "Spettro SDR" },
                    { "mw.chk.qrz", "Ricerca QRZ" },
                    { "mw.card.properties", "PROPRIET\u00c0" },
                    { "mw.nosource", "Nessuna sorgente connessa" },
                    { "mw.rx", "RX" },
                    { "mw.tunestrongest", "Sintonizza la pi\u00f9 forte" },
                    { "mw.sdrsettings", "Impostazioni SDR..." },
                    { "mw.tab.batc", "Spettro BATC" },
                    { "mw.tab.sdr", "Spettro SDR" },
                    { "mw.tab.signal", "Cronologia segnale" },
                    { "mw.tab.debug", "Debug" },
                    { "mw.clear", "Pulisci" },
                    { "mw.graph.show", "Mostra:" },
                    { "mw.graph.mer", "SNR/MER" },
                    { "mw.graph.margin", "Margine" },
                    { "mw.graph.ber", "BER" },
                    { "mw.graph.window", "Finestra:" },
                    { "mw.status.source", "Sorgente" },
                    { "mw.status.device", "Dispositivo" },
                    { "mw.status.lock", "Aggancio" },
                    { "mw.status.disk", "Disco" },
                    { "mw.status.yes", "S\u00cc" },
                    { "mw.status.no", "no" },
                    { "mw.status.free", "liberi" },
                    { "msg.connectsource", "Connetti prima una sorgente." },
                    { "mw.toast.locked", "Segnale agganciato" },
                    { "mw.toast.lost", "Segnale perso" },
                    { "mw.toast.recstart", "Registrazione avviata" },
                    { "mw.toast.recstop", "Registrazione fermata" },
                    { "mw.toast.snapshot", "Istantanea acquisita" },
                    { "mw.toast.tuned", "Sintonizzato su" },
                    { "btn.save", "Salva" },
                    { "btn.cancel", "Annulla" },
                    { "btn.close", "Chiudi" },
                    { "btn.add", "Aggiungi" },
                    { "btn.start", "Avvia" },
                    { "btn.stop", "Ferma" },
                    { "btn.refresh", "Aggiorna" },
                    { "btn.delete", "Elimina" },
                    { "btn.play", "Riproduci" },
                    { "btn.pause", "Pausa" },
                    { "btn.export", "Esporta" },
                    { "btn.import", "Importa" },
                }
            },
            { "nl", new Dictionary<string, string>
                {
                    { "mw.menu.open", "Open Tuner" },
                    { "mw.menu.settings", "Instellingen..." },
                    { "mw.menu.presets", "Frequentievoorinstellingen beheren..." },
                    { "mw.menu.disconnect", "Verbreken" },
                    { "mw.menu.dark", "Donkere modus" },
                    { "mw.menu.contrast", "Hoog contrast" },
                    { "mw.menu.language", "Taal" },
                    { "mw.menu.quit", "Afsluiten" },
                    { "mw.menu.view", "Beeld" },
                    { "mw.menu.tune", "Afstemmen op frequentie..." },
                    { "mw.menu.fullscreen", "Volledig scherm" },
                    { "mw.menu.layout", "Indelingsvoorinstellingen" },
                    { "mw.layout.1", "Enkel" },
                    { "mw.layout.2side", "Twee - naast elkaar" },
                    { "mw.layout.2stack", "Twee - gestapeld" },
                    { "mw.layout.4quad", "Vier - kwadrant" },
                    { "mw.menu.hideprops", "Eigenschappen verbergen" },
                    { "mw.menu.hidespectrum", "Spectrum verbergen" },
                    { "mw.menu.shortcuts", "Sneltoetsen..." },
                    { "mw.menu.debuglog", "Foutopsporingslog..." },
                    { "mw.menu.features", "Functies" },
                    { "mw.menu.mqttsettings", "MQTT-clientinstellingen..." },
                    { "mw.menu.quicktunesettings", "QuickTune-instellingen..." },
                    { "mw.menu.datvsettings", "DATV Reporter-instellingen..." },
                    { "mw.menu.webchatsettings", "Webchat-instellingen..." },
                    { "mw.menu.qrzsettings", "QRZ-zoekinstellingen..." },
                    { "mw.menu.webchat", "Webchat..." },
                    { "mw.menu.broadcastlistener", "PicoTuner (WH) broadcast-listener..." },
                    { "mw.menu.hardwareinfo", "Hardware-info..." },
                    { "mw.menu.externaltools", "Externe hulpmiddelen..." },
                    { "mw.menu.pluto", "Pluto-bediening..." },
                    { "mw.menu.bandscan", "Bandscanner..." },
                    { "mw.menu.beacons", "QO-100 bakens..." },
                    { "mw.menu.recordmanager", "Opnamebeheer..." },
                    { "mw.menu.gallery", "Momentopname-galerij..." },
                    { "mw.menu.help", "Help" },
                    { "mw.menu.documentation", "Documentatie" },
                    { "mw.menu.updates", "OpenTuner-updates" },
                    { "mw.menu.github", "GitHub-problemen" },
                    { "mw.menu.forums", "BATC-forums" },
                    { "mw.menu.batc", "British Amateur Television Club" },
                    { "mw.menu.article2ndts", "Artikel: 2e TS op Minitiouner" },
                    { "mw.menu.articlepico", "PicoTuner-artikel" },
                    { "mw.menu.support", "Steun (koop me een koffie)" },
                    { "mw.card.source", "BRONSELECTIE" },
                    { "mw.connect", "Verbinden" },
                    { "mw.sourcesettings", "Broninstellingen" },
                    { "mw.card.extra", "EXTRA FUNCTIES" },
                    { "mw.info", "Info" },
                    { "mw.settings", "Instellingen" },
                    { "mw.chk.batcspectrum", "BATC-spectrum (QO-100)" },
                    { "mw.chk.batchat", "BATC-chat (QO-100)" },
                    { "mw.chk.mqtt", "MQTT-client" },
                    { "mw.chk.quicktune", "Quick Tune" },
                    { "mw.chk.datv", "DATV Reporter" },
                    { "mw.chk.sdr", "SDR-spectrum" },
                    { "mw.chk.qrz", "QRZ-zoekopdracht" },
                    { "mw.card.properties", "EIGENSCHAPPEN" },
                    { "mw.nosource", "Geen bron verbonden" },
                    { "mw.rx", "RX" },
                    { "mw.tunestrongest", "Sterkste afstemmen" },
                    { "mw.sdrsettings", "SDR-instellingen..." },
                    { "mw.tab.batc", "BATC-spectrum" },
                    { "mw.tab.sdr", "SDR-spectrum" },
                    { "mw.tab.signal", "Signaalgeschiedenis" },
                    { "mw.tab.debug", "Debug" },
                    { "mw.clear", "Wissen" },
                    { "mw.graph.show", "Tonen:" },
                    { "mw.graph.mer", "SNR/MER" },
                    { "mw.graph.margin", "Marge" },
                    { "mw.graph.ber", "BER" },
                    { "mw.graph.window", "Venster:" },
                    { "mw.status.source", "Bron" },
                    { "mw.status.device", "Apparaat" },
                    { "mw.status.lock", "Vergrendeling" },
                    { "mw.status.disk", "Schijf" },
                    { "mw.status.yes", "JA" },
                    { "mw.status.no", "nee" },
                    { "mw.status.free", "vrij" },
                    { "msg.connectsource", "Verbind eerst met een bron." },
                    { "mw.toast.locked", "Signaal vergrendeld" },
                    { "mw.toast.lost", "Signaal verloren" },
                    { "mw.toast.recstart", "Opname gestart" },
                    { "mw.toast.recstop", "Opname gestopt" },
                    { "mw.toast.snapshot", "Momentopname gemaakt" },
                    { "mw.toast.tuned", "Afgestemd op" },
                    { "btn.save", "Opslaan" },
                    { "btn.cancel", "Annuleren" },
                    { "btn.close", "Sluiten" },
                    { "btn.add", "Toevoegen" },
                    { "btn.start", "Start" },
                    { "btn.stop", "Stop" },
                    { "btn.refresh", "Vernieuwen" },
                    { "btn.delete", "Verwijderen" },
                    { "btn.play", "Afspelen" },
                    { "btn.pause", "Pauze" },
                    { "btn.export", "Exporteren" },
                    { "btn.import", "Importeren" },
                }
            },
            { "pl", new Dictionary<string, string>
                {
                    { "mw.menu.open", "Open Tuner" },
                    { "mw.menu.settings", "Ustawienia..." },
                    { "mw.menu.presets", "Zarz\u0105dzaj presetami cz\u0119stotliwo\u015bci..." },
                    { "mw.menu.disconnect", "Roz\u0142\u0105cz" },
                    { "mw.menu.dark", "Tryb ciemny" },
                    { "mw.menu.contrast", "Wysoki kontrast" },
                    { "mw.menu.language", "J\u0119zyk" },
                    { "mw.menu.quit", "Zako\u0144cz" },
                    { "mw.menu.view", "Widok" },
                    { "mw.menu.tune", "Strojenie cz\u0119stotliwo\u015bci..." },
                    { "mw.menu.fullscreen", "Pe\u0142ny ekran" },
                    { "mw.menu.layout", "Presety uk\u0142adu" },
                    { "mw.layout.1", "Pojedynczy" },
                    { "mw.layout.2side", "Dwa - obok siebie" },
                    { "mw.layout.2stack", "Dwa - jeden nad drugim" },
                    { "mw.layout.4quad", "Cztery - kwadrat" },
                    { "mw.menu.hideprops", "Ukryj w\u0142a\u015bciwo\u015bci" },
                    { "mw.menu.hidespectrum", "Ukryj widmo" },
                    { "mw.menu.shortcuts", "Skr\u00f3ty klawiaturowe..." },
                    { "mw.menu.debuglog", "Dziennik debugowania..." },
                    { "mw.menu.features", "Funkcje" },
                    { "mw.menu.mqttsettings", "Ustawienia klienta MQTT..." },
                    { "mw.menu.quicktunesettings", "Ustawienia QuickTune..." },
                    { "mw.menu.datvsettings", "Ustawienia DATV Reporter..." },
                    { "mw.menu.webchatsettings", "Ustawienia czatu WWW..." },
                    { "mw.menu.qrzsettings", "Ustawienia wyszukiwania QRZ..." },
                    { "mw.menu.webchat", "Czat WWW..." },
                    { "mw.menu.broadcastlistener", "Nas\u0142uch emisji PicoTuner (WH)..." },
                    { "mw.menu.hardwareinfo", "Informacje o sprz\u0119cie..." },
                    { "mw.menu.externaltools", "Narz\u0119dzia zewn\u0119trzne..." },
                    { "mw.menu.pluto", "Sterowanie Pluto..." },
                    { "mw.menu.bandscan", "Skanowanie pasma..." },
                    { "mw.menu.beacons", "Latarnie QO-100..." },
                    { "mw.menu.recordmanager", "Mened\u017cer nagra\u0144..." },
                    { "mw.menu.gallery", "Galeria zrzut\u00f3w..." },
                    { "mw.menu.help", "Pomoc" },
                    { "mw.menu.documentation", "Dokumentacja" },
                    { "mw.menu.updates", "Aktualizacje OpenTuner" },
                    { "mw.menu.github", "Problemy na GitHub" },
                    { "mw.menu.forums", "Fora BATC" },
                    { "mw.menu.batc", "British Amateur Television Club" },
                    { "mw.menu.article2ndts", "Artyku\u0142: 2. TS w Minitiouner" },
                    { "mw.menu.articlepico", "Artyku\u0142 o PicoTuner" },
                    { "mw.menu.support", "Wsparcie (postaw mi kaw\u0119)" },
                    { "mw.card.source", "WYB\u00d3R \u0179R\u00d3D\u0141A" },
                    { "mw.connect", "Po\u0142\u0105cz" },
                    { "mw.sourcesettings", "Ustawienia \u017ar\u00f3d\u0142a" },
                    { "mw.card.extra", "DODATKOWE FUNKCJE" },
                    { "mw.info", "Info" },
                    { "mw.settings", "Ustawienia" },
                    { "mw.chk.batcspectrum", "Widmo BATC (QO-100)" },
                    { "mw.chk.batchat", "Czat BATC (QO-100)" },
                    { "mw.chk.mqtt", "Klient MQTT" },
                    { "mw.chk.quicktune", "Szybkie strojenie" },
                    { "mw.chk.datv", "DATV Reporter" },
                    { "mw.chk.sdr", "Widmo SDR" },
                    { "mw.chk.qrz", "Wyszukiwanie QRZ" },
                    { "mw.card.properties", "W\u0141A\u015aCIWO\u015aCI" },
                    { "mw.nosource", "Brak pod\u0142\u0105czonego \u017ar\u00f3d\u0142a" },
                    { "mw.rx", "RX" },
                    { "mw.tunestrongest", "Strojenie na najsilniejszy" },
                    { "mw.sdrsettings", "Ustawienia SDR..." },
                    { "mw.tab.batc", "Widmo BATC" },
                    { "mw.tab.sdr", "Widmo SDR" },
                    { "mw.tab.signal", "Historia sygna\u0142u" },
                    { "mw.tab.debug", "Debug" },
                    { "mw.clear", "Wyczy\u015b\u0107" },
                    { "mw.graph.show", "Poka\u017c:" },
                    { "mw.graph.mer", "SNR/MER" },
                    { "mw.graph.margin", "Margines" },
                    { "mw.graph.ber", "BER" },
                    { "mw.graph.window", "Okno:" },
                    { "mw.status.source", "\u0179r\u00f3d\u0142o" },
                    { "mw.status.device", "Urz\u0105dzenie" },
                    { "mw.status.lock", "Blokada" },
                    { "mw.status.disk", "Dysk" },
                    { "mw.status.yes", "TAK" },
                    { "mw.status.no", "nie" },
                    { "mw.status.free", "wolne" },
                    { "msg.connectsource", "Najpierw po\u0142\u0105cz \u017ar\u00f3d\u0142o." },
                    { "mw.toast.locked", "Sygna\u0142 zablokowany" },
                    { "mw.toast.lost", "Sygna\u0142 utracony" },
                    { "mw.toast.recstart", "Nagrywanie rozpocz\u0119te" },
                    { "mw.toast.recstop", "Nagrywanie zatrzymane" },
                    { "mw.toast.snapshot", "Zrzut wykonany" },
                    { "mw.toast.tuned", "Nastrojono na" },
                    { "btn.save", "Zapisz" },
                    { "btn.cancel", "Anuluj" },
                    { "btn.close", "Zamknij" },
                    { "btn.add", "Dodaj" },
                    { "btn.start", "Start" },
                    { "btn.stop", "Stop" },
                    { "btn.refresh", "Od\u015bwie\u017c" },
                    { "btn.delete", "Usu\u0144" },
                    { "btn.play", "Odtwarzaj" },
                    { "btn.pause", "Pauza" },
                    { "btn.export", "Eksportuj" },
                    { "btn.import", "Importuj" },
                }
            },
            { "ja", new Dictionary<string, string>
                {
                    { "mw.menu.open", "Open Tuner" },
                    { "mw.menu.settings", "\u8a2d\u5b9a..." },
                    { "mw.menu.presets", "\u5468\u6ce2\u6570\u30d7\u30ea\u30bb\u30c3\u30c8\u306e\u7ba1\u7406..." },
                    { "mw.menu.disconnect", "\u5207\u65ad" },
                    { "mw.menu.dark", "\u30c0\u30fc\u30af\u30e2\u30fc\u30c9" },
                    { "mw.menu.contrast", "\u30cf\u30a4\u30b3\u30f3\u30c8\u30e9\u30b9\u30c8" },
                    { "mw.menu.language", "\u8a00\u8a9e" },
                    { "mw.menu.quit", "\u7d42\u4e86" },
                    { "mw.menu.view", "\u8868\u793a" },
                    { "mw.menu.tune", "\u5468\u6ce2\u6570\u3092\u5408\u308f\u305b\u308b..." },
                    { "mw.menu.fullscreen", "\u5168\u753b\u9762" },
                    { "mw.menu.layout", "\u30ec\u30a4\u30a2\u30a6\u30c8\u30d7\u30ea\u30bb\u30c3\u30c8" },
                    { "mw.layout.1", "\u5358\u4e00" },
                    { "mw.layout.2side", "2\u753b\u9762 - \u4e26\u5217" },
                    { "mw.layout.2stack", "2\u753b\u9762 - \u7e26\u7a4d\u307f" },
                    { "mw.layout.4quad", "4\u753b\u9762 - \u56db\u5206\u5272" },
                    { "mw.menu.hideprops", "\u30d7\u30ed\u30d1\u30c6\u30a3\u3092\u96a0\u3059" },
                    { "mw.menu.hidespectrum", "\u30b9\u30da\u30af\u30c8\u30eb\u3092\u96a0\u3059" },
                    { "mw.menu.shortcuts", "\u30ad\u30fc\u30dc\u30fc\u30c9\u30b7\u30e7\u30fc\u30c8\u30ab\u30c3\u30c8..." },
                    { "mw.menu.debuglog", "\u30c7\u30d0\u30c3\u30b0\u30ed\u30b0..." },
                    { "mw.menu.features", "\u6a5f\u80fd" },
                    { "mw.menu.mqttsettings", "MQTT\u30af\u30e9\u30a4\u30a2\u30f3\u30c8\u8a2d\u5b9a..." },
                    { "mw.menu.quicktunesettings", "QuickTune\u8a2d\u5b9a..." },
                    { "mw.menu.datvsettings", "DATV Reporter\u8a2d\u5b9a..." },
                    { "mw.menu.webchatsettings", "Web\u30c1\u30e3\u30c3\u30c8\u8a2d\u5b9a..." },
                    { "mw.menu.qrzsettings", "QRZ\u691c\u7d22\u8a2d\u5b9a..." },
                    { "mw.menu.webchat", "Web\u30c1\u30e3\u30c3\u30c8..." },
                    { "mw.menu.broadcastlistener", "PicoTuner (WH) \u30d6\u30ed\u30fc\u30c9\u30ad\u30e3\u30b9\u30c8\u30ea\u30b9\u30ca..." },
                    { "mw.menu.hardwareinfo", "\u30cf\u30fc\u30c9\u30a6\u30a7\u30a2\u60c5\u5831..." },
                    { "mw.menu.externaltools", "\u5916\u90e8\u30c4\u30fc\u30eb..." },
                    { "mw.menu.pluto", "Pluto\u5236\u5fa1..." },
                    { "mw.menu.bandscan", "\u30d0\u30f3\u30c9\u30b9\u30ad\u30e3\u30f3..." },
                    { "mw.menu.beacons", "QO-100\u30d3\u30fc\u30b3\u30f3..." },
                    { "mw.menu.recordmanager", "\u9332\u753b\u7ba1\u7406..." },
                    { "mw.menu.gallery", "\u30b9\u30ca\u30c3\u30d7\u30b7\u30e7\u30c3\u30c8\u30ae\u30e3\u30e9\u30ea\u30fc..." },
                    { "mw.menu.help", "\u30d8\u30eb\u30d7" },
                    { "mw.menu.documentation", "\u30c9\u30ad\u30e5\u30e1\u30f3\u30c8" },
                    { "mw.menu.updates", "OpenTuner\u30a2\u30c3\u30d7\u30c7\u30fc\u30c8" },
                    { "mw.menu.github", "GitHub\u306e\u554f\u984c" },
                    { "mw.menu.forums", "BATC\u30d5\u30a9\u30fc\u30e9\u30e0" },
                    { "mw.menu.batc", "British Amateur Television Club" },
                    { "mw.menu.article2ndts", "\u8a18\u4e8b: Minitiouner\u306b\u7b2c2 TS" },
                    { "mw.menu.articlepico", "PicoTuner\u8a18\u4e8b" },
                    { "mw.menu.support", "\u30b5\u30dd\u30fc\u30c8 (\u30b3\u30fc\u30d2\u30fc\u3092\u3054\u3061\u305d\u3046)" },
                    { "mw.card.source", "\u30bd\u30fc\u30b9\u9078\u629e" },
                    { "mw.connect", "\u63a5\u7d9a" },
                    { "mw.sourcesettings", "\u30bd\u30fc\u30b9\u8a2d\u5b9a" },
                    { "mw.card.extra", "\u62e1\u5f35\u6a5f\u80fd" },
                    { "mw.info", "\u60c5\u5831" },
                    { "mw.settings", "\u8a2d\u5b9a" },
                    { "mw.chk.batcspectrum", "BATC\u30b9\u30da\u30af\u30c8\u30eb (QO-100)" },
                    { "mw.chk.batchat", "BATC\u30c1\u30e3\u30c3\u30c8 (QO-100)" },
                    { "mw.chk.mqtt", "MQTT\u30af\u30e9\u30a4\u30a2\u30f3\u30c8" },
                    { "mw.chk.quicktune", "\u30af\u30a4\u30c3\u30af\u30c1\u30e5\u30fc\u30f3" },
                    { "mw.chk.datv", "DATV Reporter" },
                    { "mw.chk.sdr", "SDR\u30b9\u30da\u30af\u30c8\u30eb" },
                    { "mw.chk.qrz", "QRZ\u691c\u7d22" },
                    { "mw.card.properties", "\u30d7\u30ed\u30d1\u30c6\u30a3" },
                    { "mw.nosource", "\u30bd\u30fc\u30b9\u304c\u63a5\u7d9a\u3055\u308c\u3066\u3044\u307e\u305b\u3093" },
                    { "mw.rx", "RX" },
                    { "mw.tunestrongest", "\u6700\u3082\u5f37\u3044\u4fe1\u53f7\u306b\u5408\u308f\u305b\u308b" },
                    { "mw.sdrsettings", "SDR\u8a2d\u5b9a..." },
                    { "mw.tab.batc", "BATC\u30b9\u30da\u30af\u30c8\u30eb" },
                    { "mw.tab.sdr", "SDR\u30b9\u30da\u30af\u30c8\u30eb" },
                    { "mw.tab.signal", "\u4fe1\u53f7\u5c65\u6b74" },
                    { "mw.tab.debug", "\u30c7\u30d0\u30c3\u30b0" },
                    { "mw.clear", "\u30af\u30ea\u30a2" },
                    { "mw.graph.show", "\u8868\u793a:" },
                    { "mw.graph.mer", "SNR/MER" },
                    { "mw.graph.margin", "\u30de\u30fc\u30b8\u30f3" },
                    { "mw.graph.ber", "BER" },
                    { "mw.graph.window", "\u671f\u9593:" },
                    { "mw.status.source", "\u30bd\u30fc\u30b9" },
                    { "mw.status.device", "\u30c7\u30d0\u30a4\u30b9" },
                    { "mw.status.lock", "\u30ed\u30c3\u30af" },
                    { "mw.status.disk", "\u30c7\u30a3\u30b9\u30af" },
                    { "mw.status.yes", "\u306f\u3044" },
                    { "mw.status.no", "\u3044\u3044\u3048" },
                    { "mw.status.free", "\u7a7a\u304d" },
                    { "msg.connectsource", "\u5148\u306b\u30bd\u30fc\u30b9\u3092\u63a5\u7d9a\u3057\u3066\u304f\u3060\u3055\u3044\u3002" },
                    { "mw.toast.locked", "\u4fe1\u53f7\u30ed\u30c3\u30af" },
                    { "mw.toast.lost", "\u4fe1\u53f7\u5931\u3044\u307e\u3057\u305f" },
                    { "mw.toast.recstart", "\u9332\u753b\u958b\u59cb" },
                    { "mw.toast.recstop", "\u9332\u753b\u505c\u6b62" },
                    { "mw.toast.snapshot", "\u30b9\u30ca\u30c3\u30d7\u30b7\u30e7\u30c3\u30c8\u3092\u4fdd\u5b58" },
                    { "mw.toast.tuned", "\u5408\u308f\u305b\u307e\u3057\u305f:" },
                    { "btn.save", "\u4fdd\u5b58" },
                    { "btn.cancel", "\u30ad\u30e3\u30f3\u30bb\u30eb" },
                    { "btn.close", "\u9589\u3058\u308b" },
                    { "btn.add", "\u8ffd\u52a0" },
                    { "btn.start", "\u958b\u59cb" },
                    { "btn.stop", "\u505c\u6b62" },
                    { "btn.refresh", "\u66f4\u65b0" },
                    { "btn.delete", "\u524a\u9664" },
                    { "btn.play", "\u518d\u751f" },
                    { "btn.pause", "\u4e00\u6642\u505c\u6b62" },
                    { "btn.export", "\u30a8\u30af\u30b9\u30dd\u30fc\u30c8" },
                    { "btn.import", "\u30a4\u30f3\u30dd\u30fc\u30c8" },
                }
            },
        };

        // ------------------------------------------------------------------
        public static void Apply(string language)
        {
            if (string.IsNullOrEmpty(language) || !Overrides.ContainsKey(language))
                language = "en";

            CurrentLanguage = language;
            Publish();
            LanguageChanged?.Invoke();
        }

        /// <summary>Resolves a key for the active language (falls back to English).</summary>
        public static string Get(string key)
        {
            if (Overrides.TryGetValue(CurrentLanguage, out var dict) && dict.TryGetValue(key, out string value))
                return value;

            if (En.TryGetValue(key, out string fallback))
                return fallback;

            return key;
        }

        /// <summary>Builds a single format-argument-free localized string.</summary>
        public static string Format(string key, params object[] args)
        {
            try { return string.Format(Get(key), args); }
            catch { return Get(key); }
        }

        /// <summary>English source key enumeration (used to publish resources).</summary>
        public static IEnumerable<string> Keys => En.Keys;

        private static void Publish()
        {
            var app = Application.Current;
            if (app == null)
                return;

            foreach (string key in En.Keys)
                app.Resources[key] = Get(key);
        }
    }
}
