<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>OpenTuner.Wpf</RootNamespace>
    <AssemblyName>opentuner.wpf</AssemblyName>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon>..\tv.ico</ApplicationIcon>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Prefer32Bit>false</Prefer32Bit>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WPF" Version="3.8.5" />
    <PackageReference Include="System.Memory" Version="4.5.5" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="System.Buffers" Version="4.5.1" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\extra\bandplan.xml">
      <Link>extra\bandplan.xml</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\opentuner.csproj" />
    <Reference Include="FlyleafLib">
      <HintPath>..\packages\FlyleafLib.3.7.50\lib\net472\FlyleafLib.dll</HintPath>
    </Reference>
    <Reference Include="NAudio">
      <HintPath>..\packages\NAudio.2.1.0\lib\net472\NAudio.dll</HintPath>
    </Reference>
    <Reference Include="NAudio.Core">
      <HintPath>..\packages\NAudio.Core.2.1.0\lib\netstandard2.0\NAudio.Core.dll</HintPath>
    </Reference>
    <Reference Include="NAudio.WinMM">
      <HintPath>..\packages\NAudio.WinMM.2.1.0\lib\netstandard2.0\NAudio.WinMM.dll</HintPath>
    </Reference>
    <Reference Include="SocketIOClient">
      <HintPath>..\packages\SocketIOClient.3.0.8\lib\net462\SocketIOClient.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>..\packages\Newtonsoft.Json.13.0.3\lib\net45\Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="FFmpeg.AutoGen">
      <HintPath>..\packages\FFmpeg.AutoGen.6.0.0\lib\netstandard2.0\FFmpeg.AutoGen.dll</HintPath>
    </Reference>
    <Reference Include="Serilog">
      <HintPath>..\packages\Serilog.3.1.2-dev-02097\lib\net471\Serilog.dll</HintPath>
    </Reference>
    <Reference Include="Serilog.Sinks.File">
      <HintPath>..\packages\Serilog.Sinks.File.5.0.0\lib\net45\Serilog.Sinks.File.dll</HintPath>
    </Reference>
  </ItemGroup>

  <Target Name="CopyFFmpegNativeLibraries" AfterTargets="Build">
    <ItemGroup>
      <FFmpegNativeLibraries Include="..\packages\FFmpeg.Stable.6.1.0\build\native\bin\x64\*.dll" />
    </ItemGroup>
    <MakeDir Directories="$(OutDir)ffmpeg" Condition="'@(FFmpegNativeLibraries)' != ''" />
    <Copy SourceFiles="@(FFmpegNativeLibraries)" DestinationFolder="$(OutDir)ffmpeg" SkipUnchangedFiles="true" Condition="'@(FFmpegNativeLibraries)' != ''" />
  </Target>

</Project>

